resources/user-data.sh
@christinaforney @ryan-blunden please merge this PR when you are ready to announce 3.5.0's release.
=> update sourcegraph version to 3.5.0

resources/user-data.sh
Part of https://github.com/sourcegraph/sourcegraph/issues/4863
=> Update user-data.sh to 3.6.0

resources/user-data.sh
Part of https://github.com/sourcegraph/sourcegraph/issues/5845
=> Update Sourcegraph to 3.9.0

resources/user-data.sh
=> release 3.9.1

resources/user-data.sh
This pull request is part of the Sourcegraph 3.22.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.22.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/15023
=> release: sourcegraph@3.22.0

resources/user-data.sh
This pull request is part of the Sourcegraph 3.22.1 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.22.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/16531)
=> release: sourcegraph@3.22.1

resources/user-data.sh
This pull request is part of the Sourcegraph 3.23.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.23.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/16108)
=> release: sourcegraph@3.23.0

resources/user-data.sh
This pull request is part of the Sourcegraph 3.24.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.24.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/17144)
=> release: sourcegraph@3.24.0

resources/user-data.sh
This pull request is part of the Sourcegraph 3.24.1 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.24.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/17770)
=> release: sourcegraph@3.24.1

resources/user-data.sh
This pull request is part of the Sourcegraph 3.25.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.25.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/17727)
=> release: sourcegraph@3.25.0

resources/user-data.sh
This pull request is part of the Sourcegraph 3.25.1 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.25.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/18609)
=> release: sourcegraph@3.25.1

resources/user-data.sh
This pull request is part of the Sourcegraph 3.25.2 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.25.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/18737)
=> release: sourcegraph@3.25.2

resources/user-data.sh
This pull request is part of the Sourcegraph 3.26.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.26.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/18640)
=> release: sourcegraph@3.26.0

resources/user-data.sh
This pull request is part of the Sourcegraph 3.26.1 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.26.1)
* No tracking issue exists for this release
=> release: sourcegraph@3.26.1

resources/user-data.sh
This pull request is part of the Sourcegraph 3.26.2 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.26.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/19775)
=> release: sourcegraph@3.26.2

resources/user-data.sh
This pull request is part of the Sourcegraph 3.26.3 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.26.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/19840)
=> release: sourcegraph@3.26.3

resources/user-data.sh
This pull request is part of the Sourcegraph 3.27.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.27.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/19746)
=> release: sourcegraph@3.27.0

resources/user-data.sh
This pull request is part of the Sourcegraph 3.27.1 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.27.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/20315)
=> release: sourcegraph@3.27.1

resources/user-data.sh
This pull request is part of the Sourcegraph 3.27.2 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.27.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/20377)
=> release: sourcegraph@3.27.2

resources/user-data.sh
This pull request is part of the Sourcegraph 3.27.3 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.27.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/20420)
=> release: sourcegraph@3.27.3

resources/user-data.sh
This pull request is part of the Sourcegraph 3.27.5 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.27.5)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/20948)
=> release: sourcegraph@3.27.5

resources/user-data.sh
This pull request is part of the Sourcegraph 3.28.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.28.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/20996)
=> release: sourcegraph@3.28.0

resources/user-data.sh
This pull request is part of the Sourcegraph 3.29.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.29.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/21370)
=> release: sourcegraph@3.29.0

resources/user-data.sh
This pull request is part of the Sourcegraph 3.29.1 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.29.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/22397)
=> release: sourcegraph@3.29.1

resources/user-data.sh
This pull request is part of the Sourcegraph 3.30.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.30.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/22300)
=> release: sourcegraph@3.30.0

resources/user-data.sh
This pull request is part of the Sourcegraph 3.30.1 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.30.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/23143)
=> release: sourcegraph@3.30.1

resources/user-data.sh
This pull request is part of the Sourcegraph 3.30.2 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.30.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/23304)
=> release: sourcegraph@3.30.2

resources/user-data.sh
This pull request is part of the Sourcegraph 3.30.3 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch changes/release-sourcegraph-3.30.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/23326)
=> release: sourcegraph@3.30.3

resources/user-data.sh
This pull request is part of the Sourcegraph 3.30.4 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.30.4)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/23996)
=> release: sourcegraph@3.30.4

resources/user-data.sh
This pull request is part of the Sourcegraph 3.31.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.31.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/24515)
=> release: sourcegraph@3.31.1

resources/user-data.sh
This pull request is part of the Sourcegraph 3.31.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.31.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/24737)
=> release: sourcegraph@3.31.2

resources/user-data.sh
This pull request is part of the Sourcegraph 3.32.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.32.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/25002)
=> release: sourcegraph@3.32.0

resources/user-data.sh
This pull request is part of the Sourcegraph 3.33.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.33.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/27855)
=> release: sourcegraph@3.33.1

resources/user-data.sh
This pull request is part of the Sourcegraph 3.34.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.34.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/26714)
=> release: sourcegraph@3.34.0

resources/user-data.sh
This pull request is part of the Sourcegraph 3.34.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.34.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/28104)
=> release: sourcegraph@3.34.1

resources/user-data.sh
This pull request is part of the Sourcegraph 3.34.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.34.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/28640)
=> release: sourcegraph@3.34.2

resources/user-data.sh
This pull request is part of the Sourcegraph 3.35.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.35.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/28613)
=> release: sourcegraph@3.35.0

resources/user-data.sh
This pull request is part of the Sourcegraph 3.35.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.35.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/29403)
=> release: sourcegraph@3.35.1

resources/user-data.sh
This pull request is part of the Sourcegraph 3.36.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.36.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/29290)
=> release: sourcegraph@3.36.0

resources/user-data.sh
This pull request is part of the Sourcegraph 3.36.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.36.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30041)
=> release: sourcegraph@3.36.1

resources/user-data.sh
This pull request is part of the Sourcegraph 3.36.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.36.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30200)
=> release: sourcegraph@3.36.2

resources/user-data.sh
This pull request is part of the Sourcegraph 3.36.3 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.36.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30562)
=> release: sourcegraph@3.36.3

resources/user-data.sh
This pull request is part of the Sourcegraph 3.37.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.37.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30051)
=> release: sourcegraph@3.37.0

resources/user-data.sh
This pull request is part of the Sourcegraph 3.38.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.38.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/31768)
=> release: sourcegraph@3.38.0

resources/user-data.sh
This pull request is part of the Sourcegraph 3.38.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.38.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/33457)
=> release: sourcegraph@3.38.1

resources/user-data.sh
This pull request is part of the Sourcegraph 3.39.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.39.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/32836)
=> release: sourcegraph@3.39.0

resources/user-data.sh
This pull request is part of the Sourcegraph 3.39.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.39.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/34545)
=> release: sourcegraph@3.39.1

resources/user-data.sh
This pull request is part of the Sourcegraph 3.40.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.40.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/34255)
=> release: sourcegraph@3.40.0

resources/user-data.sh
This pull request is part of the Sourcegraph 3.40.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.40.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/36218)
=> release: sourcegraph@3.40.1

resources/user-data.sh
This pull request is part of the Sourcegraph 3.40.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.40.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/36790)
=> release: sourcegraph@3.40.2

resources/user-data.sh
This pull request is part of the Sourcegraph 3.41.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.41.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/37183)
=> release: sourcegraph@3.41.0

resources/user-data.sh
This pull request is part of the Sourcegraph 3.41.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.41.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/38644)
=> release: sourcegraph@3.41.1

resources/user-data.sh
This pull request is part of the Sourcegraph 3.42.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.42.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/38119)
=> release: sourcegraph@3.42.0

resources/user-data.sh
This pull request is part of the Sourcegraph 3.42.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.42.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/39596)
=> release: sourcegraph@3.42.1

resources/user-data.sh
This pull request is part of the Sourcegraph 3.42.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.42.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/40031)
=> release: sourcegraph@3.42.2

resources/user-data.sh
This pull request is part of the Sourcegraph 3.43.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.43.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/39333)
=> release: sourcegraph@3.43.0

resources/user-data.sh
This pull request is part of the Sourcegraph 3.43.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.43.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/40986)
=> release: sourcegraph@3.43.1

resources/user-data.sh
This pull request is part of the Sourcegraph 3.43.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.43.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/41485)
=> release: sourcegraph@3.43.2

resources/user-data.sh
This pull request is part of the Sourcegraph 4.0.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.0.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/41759)
=> release: sourcegraph@4.0.0

resources/user-data.sh
This pull request is part of the Sourcegraph 4.0.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.0.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/42112)
=> release: sourcegraph@4.0.1

resources/user-data.sh
This pull request is part of the Sourcegraph 4.1.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.1.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/43468)
=> release: sourcegraph@4.1.1

resources/user-data.sh
This pull request is part of the Sourcegraph 4.1.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.1.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/43612)
=> release: sourcegraph@4.1.2

resources/user-data.sh
This pull request is part of the Sourcegraph 4.1.3 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.1.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/44078)
=> release: sourcegraph@4.1.3

resources/user-data.sh
This pull request is part of the Sourcegraph 4.2.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.2.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/43423)
=> release: sourcegraph@4.2.0

resources/user-data.sh
This pull request is part of the Sourcegraph 4.3.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.3.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/45566)
=> release: sourcegraph@4.3.0

resources/user-data.sh
This pull request is part of the Sourcegraph 4.3.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.3.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/46161)
=> release: sourcegraph@4.3.1

resources/user-data.sh
This pull request is part of the Sourcegraph 4.4.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.4.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/45780)
=> release: sourcegraph@4.4.0

resources/user-data.sh
This pull request is part of the Sourcegraph 4.4.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.4.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/46931)
=> release: sourcegraph@4.4.1

resources/user-data.sh
This pull request is part of the Sourcegraph 4.4.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.4.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/47256)
=> release: sourcegraph@4.4.2

resources/user-data.sh
This pull request is part of the Sourcegraph 4.5.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.5.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/47836)
=> release: sourcegraph@4.5.0

resources/user-data.sh
This pull request is part of the Sourcegraph 4.5.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.5.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/48151)
=> release: sourcegraph@4.5.1

resources/user-data.sh
This pull request is part of the Sourcegraph 5.0.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/50405)
=> release: sourcegraph@5.0.1

resources/user-data.sh
This pull request is part of the Sourcegraph 5.0.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/50811)
=> release: sourcegraph@5.0.2

resources/user-data.sh
This pull request is part of the Sourcegraph 5.0.3 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/51302)
=> release: sourcegraph@5.0.3

resources/user-data.sh
This pull request is part of the Sourcegraph 5.0.4 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.4)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/52092)
=> release: sourcegraph@5.0.4

resources/user-data.sh
This pull request is part of the Sourcegraph 5.0.5 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.5)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/52745)
=> release: sourcegraph@5.0.5

resources/user-data.sh
This pull request is part of the Sourcegraph 5.0.6 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.6)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/53491)
=> release: sourcegraph@5.0.6

resources/user-data.sh
This pull request is part of the Sourcegraph 5.1.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/49918)
=> release: sourcegraph@5.1.0

resources/user-data.sh
This pull request is part of the Sourcegraph 5.1.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/54459)
=> release: sourcegraph@5.1.1

resources/user-data.sh
This pull request is part of the Sourcegraph 5.1.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/54543)
=> release: sourcegraph@5.1.2

resources/user-data.sh
This pull request is part of the Sourcegraph 5.1.3 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/54899)
=> release: sourcegraph@5.1.3

resources/user-data.sh
This pull request is part of the Sourcegraph 5.1.4 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.4)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/55025)
=> release: sourcegraph@5.1.4

resources/user-data.sh
This pull request is part of the Sourcegraph 5.1.6 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.6)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/55718)
=> release: sourcegraph@5.1.6

resources/user-data.sh
This pull request is part of the Sourcegraph 5.1.7 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.7)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/56213)
=> release: sourcegraph@5.1.7

resources/user-data.sh
This pull request is part of the Sourcegraph 5.1.8 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.8)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/56395)
=> release: sourcegraph@5.1.8

resources/user-data.sh
This pull request is part of the Sourcegraph 5.1.9 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.9)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/56794)
=> release: sourcegraph@5.1.9

resources/user-data.sh
This pull request is part of the Sourcegraph 5.2.0 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/56907)
=> release: sourcegraph@5.2.0

resources/user-data.sh
This pull request is part of the Sourcegraph 5.2.1 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/57319)
=> release: sourcegraph@5.2.1

resources/user-data.sh
This pull request is part of the Sourcegraph 5.2.4 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.4)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/58662)
=> release: sourcegraph@5.2.4

resources/user-data.sh
This pull request is part of the Sourcegraph 5.2.5 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.5)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/58967)
=> release: sourcegraph@5.2.5

resources/user-data.sh
This pull request is part of the Sourcegraph 5.2.6 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.6)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/59481)
=> release: sourcegraph@5.2.6

resources/user-data.sh
This pull request is part of the Sourcegraph 5.2.7 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.7)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/59830)
=> release: sourcegraph@5.2.7

resources/user-data.sh
This pull request is part of the Sourcegraph 5.3.0 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/60032)
=> release: sourcegraph@5.3.0

resources/user-data.sh
This pull request is part of the Sourcegraph 5.3.1 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/60691)
=> release: sourcegraph@5.3.1

resources/user-data.sh
This pull request is part of the Sourcegraph 5.3.2 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/60972)
=> release: sourcegraph@5.3.2

resources/user-data.sh
This pull request is part of the Sourcegraph 5.3.3 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/61302)
=> release: sourcegraph@5.3.3
